---
# tasks file for installPython
- name: Ensure python is installed
  become: true
  block:
  
    - name: Check OS
      raw: cat /etc/os-release # Store OS information in a variable to use in subsequent tasks
      register: os_release
      changed_when: false
      failed_when: "'Debian' not in os_release.stdout and 'Ubuntu' not in os_release.stdout and 'Raspbian' not in os_release.stdout"

    - name: Check if python is installed
      raw: python3 --version
      register: python_check
      changed_when: false

    - name: Install python using raw module
      raw: apt update && apt install python3 -y
      when: python_check.rc != 0