---
# tasks file for setupDocker
- name: Set Up Docker
  become: true
  block:

  - name: Install required dependencies
    ansible.builtin.apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes

  - name: Add Docker GPG key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Install or update Docker and dependencies
    ansible.builtin.apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: yes

  - name: Install or update Docker Compose (V2)
    ansible.builtin.apt:
      name: docker-compose-plugin
      state: latest
      update_cache: yes

  - name: Add User To Docker Group
    ansible.builtin.user:
      name: "{{ansible_user}}"
      groups: docker
      append: yes

  - name: Enable & Start Docker Service
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  - name: Run 'hello-world' Container To Test If Docker Is Working
    community.docker.docker_container:
      name: hello-world
      image: hello-world
      state: started