---
# Setup HA Core & Add-ons using docker containers
- name: Python Installation
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - installPython

- name: HA Setup
  hosts: all
  any_errors_fatal: true
  gather_facts: true
  roles:
    - setupSSH
    - updateAndInstallPackages
    - preventRfkillFromBlockingWifi
    - configureUserEnvironment
    - setupDocker
    - setupHAFilesAndDirectories
    - initializeHAConfigFiles
    - adjustHAConfigFiles
    - setupHAAddOns
    - runHA