---
# Setup HA Core & Add-ons using docker containers
- name: Python Installation
  hosts: all
  any_errors_fatal: true
  gather_facts: false
  roles:
    - installPython

- name: HA Setup
  hosts: all
  any_errors_fatal: true
  gather_facts: true
  roles:
    - setupSSH
    - updateAndInstallPackages
    - preventRfkillFromBlockingWifi
    - configureUserEnvironment
    - setupRDP
    - setupDocker
    - setupHAFilesAndDirectories
    - initializeHAConfigFiles
    - adjustHAConfigFiles
    - setupHAAddOns
    - runHA


# # Install python so ansible can run using its other modules
# - name: Install python using raw module
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - installPython

# # Disable password based SSH for security reasons
# - name: Disable password authentication for SSH, and use public key authentication instead
#   hosts: all
#   roles:
#     - setupSSH

# # Update System & Install Useful Packages
# - name: Update OS and Install Useful CLI Tools on Debian-Based Systems
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - updateAndInstallPackages

# # Prevent rfkill from blocking wifi on startup - common on raspberry pi
# - name: Allow wifi/bluetooth on start - insert 'rfkill unblock wifi' into /etc/rc.local
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - preventRfkillFromBlockingWifi

# # Configure environment for user preference
# - name: Configure User Environment
#   hosts: all
#   roles:
#     - configureUserEnvironment

# # Setup RDP
# - name: Setup RDP
#   hosts: all
#   roles:
#     - setupRDP

# # docker setup
# - name: Setup Docker
#   hosts: all
#   become: true
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - setupDocker

# # Setup HA Required Directories & Files
# - name: Setup Home Assistant Required Directories & Files
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - setupHAFilesAndDirectories
  
# # Initialize HA-Related Config Files by Starting & Stopping Containers
# - name: Start and stop containers to initialize home assistant config files
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - initializeHAConfigFiles

# # Adjust HA-Related Config Files
# - name: Amend home assistant configuration
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - adjustHAConfigFiles

# # Setup/Update HA Add-Ons
# - name: Setup Add-ons for home assistant # HACS installation script does some finding of the correct working directory
#   hosts: all
#   any_errors_fatal: true
#   roles:
#     - setupHAAddOns

# # Final Run
# - name: Start docker containers and run home assistant
#   hosts: all
#   any_errors_fatal: true # Stop entire playbook if this play fails
#   roles:
#     - runHA